###########
# site.title

title:    'THE WALKING DEAD'
subtitle: 'CS 175: Project in AI (in Minecraft)'
theme: minima

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
